# Generated by Django 4.2.5 on 2025-12-28 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("incidents", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="escalationlevel",
            name="user",
        ),
        migrations.AddField(
            model_name="escalationlevel",
            name="notification_channel",
            field=models.CharField(
                default="admin",
                help_text="Email, Slack channel, PagerDuty ID, etc",
                max_length=100,
            ),
        ),
    ]
